wandb_version: 1

path:
  desc: null
  value: wandb_test
_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704774099.847679
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
